on:
  push: ~

jobs:
  compile:
    runs-on: ubuntu-22.04
    name: Compile
    strategy:
      matrix:
        GOOS:
          - linux
        GOARCH:
          - arm64
          - x64
          - "386"
          - s390x
          - mips
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: gomod-

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      
      - name: Go Get
        run: go get -v

      - name: Build
        run: go build -o rezkit
        env:
          GOOS: ${{matrix.GOOS}}
          GOARCH: ${{matrix.GOARCH}}